# Permalinks
permalink:           pretty

# Setup
title:               Macaw AI
tagline:             It's a jungle out there
url:                 http://macawai.github.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Michael Anderson & Clint Walker
  url:               https://macawai.github.io
  email:             themacawai@gmail.com


# Collections
collections:
  weekly:
    output: true
    permalink: /:collection/:year-:month-:day-:title

exclude:
  - scripts
  - README.md

include:
  - _pages

# Gems
gems:
  - octopress-paginate
  - jekyll-gist
